apiVersion: v1
kind: Pod
metadata:
  name: nilay-ner-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: training
      image: ghcr.io/offendo/ner:latest
      command: ["sleep", "infinity"]
      workingDir: /app/
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: nilay-data-volume-rwm-central
          mountPath: /volume
        - name: api-tokens
          mountPath: /etc/api-tokens
      resources:
        limits:
          memory: 32Gi
          cpu: 4
          nvidia.com/gpu: "1"
        requests:
          memory: 32Gi
          cpu: 4
          nvidia.com/gpu: "1"
  initContainers:
    - name: git-sync
      image: registry.k8s.io/git-sync/git-sync:v4.1.0
      args:
        - "--repo=git@github.com:offendo/tex-ner"
        - "--depth=1"
        - "--one-time"
        - "--root=/git"
      resources:
        limits:
          memory: 4Gi
          cpu: 1
        requests:
          memory: 4Gi
          cpu: 1
      volumeMounts:
        - name: git-repo
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
    - name: chmod
      image: alpine:latest
      command: ["chmod", "-R", "a+rw", "/volume"]
      volumeMounts:
        - name: nilay-data-volume-rwm-central
          mountPath: /volume
  securityContext:
    fsGroup: 101
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: git-secret
      secret:
        defaultMode: 0400
        secretName: nilay-git-creds
    - name: nilay-data-volume-rwm-central
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-central
    - name: api-tokens
      secret:
        defaultMode: 0400
        secretName: nilay-api-tokens
  restartPolicy: Never
