apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-ner-train-name-ref
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A100-SXM4-80GB
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-GeForce-RTX-3090
      imagePullSecrets:
        - name: nilay-ghcr-key
      containers:
        - name: trainer
          image: ghcr.io/offendo/ner:latest
          env:
            - name: RUN_NAME
              value: name-ref-finetuned
            - name: CRF
              value: "--crf"
            - name: CLASSES
              value: "--name --reference -n name -n reference"
            - name: DO_TRAIN
              value: "true"
            - name: TRAIN_FLAGS
              value: "--steps 1948 --checkpoint /volume/ner/outputs/name-only-base-model/checkpoint-best/"
            - name: DATASET
              value: roberta-base-refs
            - name: LEARNING_RATE
              value: "0.00005987474910461403"
            - name: BATCH_SIZE
              value: "16"
            - name: LABEL_SMOOTHING
              value: "0.006505159298527952"
            - name: WARMUP_RATIO
              value: "0.08599404067363206"
            - name: DROPOUT
              value: "0.0"
            - name: WEIGHT_DECAY
              value: "0.00010988100318524612"
            - name: SCHEDULER
              value: "linear"
          command: ["bash", "run.sh"]
          workingDir: /app/tex-ner
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: nilay-data-volume-rwm-east
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
          resources:
            limits:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 100Gi
            requests:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 100Gi
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.1.0
          args:
            - "--repo=git@github.com:offendo/tex-ner"
            - "--depth=1"
            - "--one-time"
            - "--root=/git"
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: git-repo
              mountPath: /git
            - name: git-secret
              mountPath: /etc/git-secret
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rw", "/volume"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm-east
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            defaultMode: 0400
            secretName: nilay-git-creds
        - name: nilay-data-volume-rwm-east
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm-east
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
      restartPolicy: Never
  backoffLimit: 0
