apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-ner-proofs
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A100-SXM4-80GB
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-GeForce-RTX-3090
      imagePullSecrets:
        - name: nilay-ghcr-key
      containers:
        - name: trainer
          image: ghcr.io/offendo/ner:latest
          env:
            - name: RUN_NAME
              value: only-proofs
            - name: CLASSES
              value: "--definition --theorem --proof --example"
            - name: DATASET
              value: roberta-base-semitight
          command: ["bash", "run.sh"]
          workingDir: /app/tex-ner
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: nilay-data-volume-rwm-central
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
          resources:
            limits:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 100Gi
            requests:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 100Gi
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.1.0
          args:
            - "--repo=git@github.com:offendo/tex-ner"
            - "--depth=1"
            - "--one-time"
            - "--root=/git"
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: git-repo
              mountPath: /git
            - name: git-secret
              mountPath: /etc/git-secret
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rw", "/volume"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm-central
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            defaultMode: 0400
            secretName: nilay-git-creds
        - name: nilay-data-volume-rwm-central
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm-central
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
      restartPolicy: Never
  backoffLimit: 0
