apiVersion: v1
kind: Pod
metadata: 
  name: nilay-pod
spec:
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: pod
      image: ubuntu:latest
      command: ["sleep", "21600"] # 6 hours - max pod time
      workingDir: /
      volumeMounts:
        - name: nilay-data-volume-rwm-east
          mountPath: /volume-east
        - name: nilay-data-volume-rwm-central
          mountPath: /volume-central
      resources:
        limits:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
        requests:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
  securityContext:
    fsGroup: 101
  volumes:
    - name: nilay-data-volume-rwm-east
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-east
    - name: nilay-data-volume-rwm-central
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-central
  restartPolicy: Never
