apiVersion: v1
kind: Pod
metadata: 
  name: nilay-pod
spec:
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: pod
      image: ghcr.io/offendo/ner:latest
      command: ["sleep", "infinity"]
      workingDir: /
      volumeMounts:
        - name: nilay-data-volume-rwm-east
          mountPath: /volume
      resources:
        limits:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
        requests:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
  securityContext:
    fsGroup: 101
  volumes:
    - name: nilay-data-volume-rwm-east
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-east
  restartPolicy: Never
